CREATE TABLE persons (
  Id INT AUTO_INCREMENT  PRIMARY KEY,
  FirstName VARCHAR(250) NOT NULL,
  LastName VARCHAR(250) NOT NULL,
  Email VARCHAR(250) NOT NULL,
  Phone VARCHAR(100) NOT NULL
);

CREATE TABLE books (
  `Id` INT AUTO_INCREMENT  PRIMARY KEY,
  `Title` varchar(255) NOT NULL,
  `Author` varchar(100) NOT NULL,
  `ISBN` varchar(20) NOT NULL
);

CREATE TABLE loans (
  `Id` INT AUTO_INCREMENT  PRIMARY KEY,
  `BookId` varchar(255) NOT NULL,
  `PersonId` varchar(100) NOT NULL,
  CONSTRAINT FK_LOAN_BOOK FOREIGN KEY (BookId) REFERENCES books(Id),
  CONSTRAINT FK_LOAN_PERSON FOREIGN KEY (PersonId) REFERENCES persons(Id)
);
